package tools

// Shared shapes for the ITIL records, which nest notes, tasks and time
// entries the same way tickets do.
func itilChildren(base string) []View {
	return []View{
		{Action: "notes", Help: "notes of id.", Path: base + "/{id}/notes", List: true},
		{Action: "note", Help: "note params.note_id of id.", Path: base + "/{id}/notes/{note_id}"},
		{Action: "tasks", Help: "tasks of id.", Path: base + "/{id}/tasks", List: true},
		{Action: "task", Help: "task params.task_id of id.", Path: base + "/{id}/tasks/{task_id}"},
		{Action: "time_entries", Help: "time entries of id.", Path: base + "/{id}/time_entries", List: true},
		{Action: "time_entry", Help: "time entry params.time_entry_id of id.", Path: base + "/{id}/time_entries/{time_entry_id}"},
	}
}

var (
	problemBrief = []string{"id", "subject", "status", "priority", "impact", "agent_id", "group_id", "department_id", "category", "workspace_id", "due_by", "created_at", "updated_at"}
	changeBrief  = []string{"id", "subject", "status", "priority", "impact", "risk", "change_type", "agent_id", "group_id", "department_id", "category", "workspace_id",
		"planned_start_date", "planned_end_date", "created_at", "updated_at"}
	releaseBrief = []string{"id", "subject", "status", "priority", "release_type", "agent_id", "group_id", "department_id", "category", "workspace_id",
		"planned_start_date", "planned_end_date", "created_at", "updated_at"}
	assetBrief = []string{"id", "display_id", "name", "asset_type_id", "asset_tag", "impact", "usage_type", "user_id", "department_id", "location_id",
		"agent_id", "group_id", "workspace_id", "created_at", "updated_at"}
)

var readTools = []Tool{
	// itil
	{Name: "freshservice_problem", Group: "itil", Title: "Problems",
		Description: "Problem records (root causes behind incidents), with notes, tasks and time entries. status: 1 Open, 2 Change Requested, 3 Closed. priority 1-4 as tickets.",
		Views: append([]View{
			{Action: "list", Help: "problems, newest first.", Path: "/api/v2/problems", List: true, Brief: problemBrief, WS: WSAll, AllNote: true},
			{Action: "get", Help: "problem id in full.", Path: "/api/v2/problems/{id}", Link: "/itil/problems/{id}"},
			{Action: "fields", Help: "problem form fields and their choices.", Path: "/api/v2/problem_form_fields", WS: WSOne},
		}, append(itilChildren("/api/v2/problems"), summaries(View{Path: "/api/v2/problems", ScanPath: "/api/v2/problems", WS: WSAll})...)...)},
	{Name: "freshservice_change", Group: "itil", Title: "Changes and CABs",
		Description: "Change requests, their approvals, notes, tasks and time entries, and Change Advisory Boards. " +
			"status: 1 Open, 2 Planning, 3 Awaiting Approval, 4 Pending Release, 5 Pending Review, 6 Closed. change_type: 1 Minor, 2 Standard, 3 Major, 4 Emergency. risk: 1 Low, 2 Medium, 3 High, 4 Very High.",
		Views: append([]View{
			{Action: "list", Help: "changes, newest first; params updated_since.", Path: "/api/v2/changes", List: true, Brief: changeBrief, WS: WSAll, AllNote: true},
			{Action: "filter", Help: "changes matching query (fields: status, priority, risk, change_type, agent_id, group_id, planned_start_date, planned_end_date, created_at, updated_at).",
				Path: "/api/v2/changes", List: true, Filter: "query", Brief: changeBrief, WS: WSAll, AllNote: true},
			{Action: "get", Help: "change id in full.", Path: "/api/v2/changes/{id}", Link: "/itil/changes/{id}"},
			{Action: "fields", Help: "change form fields and their choices.", Path: "/api/v2/change_form_fields", WS: WSOne},
			{Action: "approvals", Help: "approvals of change id.", Path: "/api/v2/changes/{id}/approvals", List: true},
			{Action: "approval", Help: "approval params.approval_id of change id.", Path: "/api/v2/changes/{id}/approvals/{approval_id}"},
			{Action: "approval_groups", Help: "approval groups of change id.", Path: "/api/v2/changes/{id}/approval-groups"},
			{Action: "cabs", Help: "Change Advisory Boards.", Path: "/api/v2/cabs", List: true},
			{Action: "cab", Help: "CAB id.", Path: "/api/v2/cabs/{id}"},
		}, append(itilChildren("/api/v2/changes"), summaries(View{Path: "/api/v2/changes", Filter: "query", ScanPath: "/api/v2/changes", WS: WSAll})...)...)},
	{Name: "freshservice_release", Group: "itil", Title: "Releases and post-incident report templates",
		Description: "Releases, with notes, tasks and time entries; and post-incident report (PIR) templates. release_type: 1 Minor, 2 Standard, 3 Major, 4 Emergency.",
		Views: append([]View{
			{Action: "list", Help: "releases, newest first.", Path: "/api/v2/releases", List: true, Brief: releaseBrief, WS: WSAll, AllNote: true},
			{Action: "filter", Help: "releases matching query (fields: status, priority, release_type, agent_id, group_id, planned_start_date, planned_end_date, created_at, updated_at).",
				Path: "/api/v2/releases", List: true, Filter: "query", Brief: releaseBrief, WS: WSAll, AllNote: true},
			{Action: "get", Help: "release id in full.", Path: "/api/v2/releases/{id}", Link: "/itil/releases/{id}"},
			{Action: "fields", Help: "release form fields and their choices.", Path: "/api/v2/release_form_fields", WS: WSOne},
			{Action: "pir_templates", Help: "post-incident report templates.", Path: "/api/v2/post-incident-reports/templates", List: true},
			{Action: "pir_template", Help: "post-incident report template id.", Path: "/api/v2/post-incident-reports/templates/{id}"},
		}, append(itilChildren("/api/v2/releases"), summaries(View{Path: "/api/v2/releases", Filter: "query", ScanPath: "/api/v2/releases", WS: WSAll})...)...)},

	// assets
	{Name: "freshservice_asset", Group: "assets", Title: "Assets, CMDB relationships and asset types",
		Description: "Assets (CMDB configuration items) on whichever asset API this account has: classic or ITAM (freshservice_status says which). " +
			"On the classic API, id is the asset's Display ID, the number agents see in Freshservice. Component, contract, request and assignment actions are classic only; " +
			"device, subtype, lifecycle and cloud actions are ITAM only.",
		Views: append([]View{
			{Action: "list", Help: "assets; params include (type_fields), order_by, order_type, trashed.", Path: "{assets}", List: true, Brief: assetBrief, WS: WSAll, AllNote: true},
			{Action: "filter", Help: "assets matching query (fields: asset_type_id, department_id, location_id, asset_state, user_id, agent_id, name, asset_tag, created_at, updated_at, custom fields). At most 1,200 results.",
				Path: "{assets}", List: true, Filter: "filter", Brief: assetBrief, WS: WSAll, AllNote: true},
			{Action: "search", Help: "assets matching params.search, e.g. \"name:'dell'\" or \"serial_number:'X1'\".", Path: "{assets}", List: true, Brief: assetBrief, WS: WSAll, AllNote: true},
			{Action: "get", Help: "asset id in full; params include (type_fields).", Path: "{assets}/{id}"},
			{Action: "assignment_history", Help: "who held asset id over time.", Path: "/api/v2/assets/{id}/assignment-history"},
			{Action: "components", Help: "hardware components of asset id.", Path: "/api/v2/assets/{id}/components"},
			{Action: "contracts", Help: "contracts covering asset id.", Path: "/api/v2/assets/{id}/contracts"},
			{Action: "requests", Help: "tickets associated with asset id.", Path: "/api/v2/assets/{id}/requests", List: true},
			{Action: "relationships", Help: "CMDB relationships of asset id.", Path: "/api/v2/assets/{id}/relationships"},
			{Action: "all_relationships", Help: "every CMDB relationship in the account.", Path: "/api/v2/relationships", List: true},
			{Action: "relationship", Help: "relationship id.", Path: "/api/v2/relationships/{id}"},
			{Action: "relationship_types", Help: "CMDB relationship types.", Path: "/api/v2/relationship_types", List: true},
			{Action: "types", Help: "asset types.", Path: "/api/v2/asset_types", List: true},
			{Action: "type", Help: "asset type id.", Path: "/api/v2/asset_types/{id}"},
			{Action: "type_fields", Help: "fields of asset type id.", Path: "/api/v2/asset_types/{id}/fields"},
			{Action: "devices", Help: "ITAM devices.", Path: "/api/v2/itam/devices", List: true},
			{Action: "device", Help: "ITAM device id.", Path: "/api/v2/itam/devices/{id}"},
			{Action: "physical_subtypes", Help: "ITAM physical subtypes.", Path: "/api/v2/itam/physical-subtypes", List: true},
			{Action: "physical_subtype", Help: "ITAM physical subtype id.", Path: "/api/v2/itam/physical-subtypes/{id}"},
			{Action: "lifecycle_events", Help: "ITAM lifecycle events.", Path: "/api/v2/itam/lifecycle_events", List: true},
			{Action: "lifecycle_event", Help: "ITAM lifecycle event id.", Path: "/api/v2/itam/lifecycle_events/{id}"},
			{Action: "cloud_resources", Help: "ITAM cloud resources.", Path: "/api/v2/itam/resources", List: true},
			{Action: "cloud_resource", Help: "ITAM cloud resource id.", Path: "/api/v2/itam/resources/{id}"},
			{Action: "cloud_relationships", Help: "ITAM cloud resource relationships.", Path: "/api/v2/itam/resource_relationships", List: true},
			{Action: "cloud_infrastructures", Help: "ITAM cloud infrastructure details.", Path: "/api/v2/itam/cloud_infrastructures"},
		}, summaries(View{Path: "{assets}", Filter: "filter", ScanPath: "{assets}", WS: WSAll})...)},
	{Name: "freshservice_software", Group: "assets", Title: "Software",
		Description: "Software applications discovered or managed in Freshservice, with installations, licenses and users.",
		Views: []View{
			{Action: "list", Help: "software applications.", Path: "/api/v2/applications", List: true, WS: WSAll},
			{Action: "get", Help: "software id.", Path: "/api/v2/applications/{id}"},
			{Action: "installations", Help: "installations of software id.", Path: "/api/v2/applications/{id}/installations", List: true},
			{Action: "licenses", Help: "licenses of software id.", Path: "/api/v2/applications/{id}/licenses", List: true},
			{Action: "relationships", Help: "relationships of software id.", Path: "/api/v2/applications/{id}/relationships", List: true},
			{Action: "users", Help: "users of software id.", Path: "/api/v2/applications/{id}/users", List: true},
			{Action: "user", Help: "software user params.user_id of software id.", Path: "/api/v2/applications/{id}/users/{user_id}"},
		}},
	{Name: "freshservice_contract", Group: "assets", Title: "Contracts",
		Description: "Contracts (lease, maintenance, software license, warranty) and the assets they cover.",
		Views: []View{
			{Action: "list", Help: "contracts.", Path: "/api/v2/contracts", List: true, WS: WSAll},
			{Action: "get", Help: "contract id.", Path: "/api/v2/contracts/{id}"},
			{Action: "assets", Help: "assets covered by contract id.", Path: "/api/v2/contracts/{id}/associated-assets", List: true},
			{Action: "attachments", Help: "attachments of contract id.", Path: "/api/v2/contracts/{id}/attachments"},
			{Action: "types", Help: "contract types.", Path: "/api/v2/contract_types", List: true},
			{Action: "type_fields", Help: "fields of contract type id.", Path: "/api/v2/contract_types/{id}/fields"},
		}},
	{Name: "freshservice_procurement", Group: "assets", Title: "Vendors, products and purchase orders",
		Description: "Vendors, the product catalog assets are bought from, and purchase orders.",
		Views: []View{
			{Action: "vendors", Help: "vendors.", Path: "/api/v2/vendors", List: true},
			{Action: "vendor", Help: "vendor id.", Path: "/api/v2/vendors/{id}"},
			{Action: "products", Help: "products.", Path: "/api/v2/products", List: true},
			{Action: "product", Help: "product id.", Path: "/api/v2/products/{id}"},
			{Action: "purchase_orders", Help: "purchase orders.", Path: "/api/v2/purchase_orders", List: true, WS: WSAll},
			{Action: "purchase_order", Help: "purchase order id.", Path: "/api/v2/purchase_orders/{id}"},
		}},

	// knowledge
	{Name: "freshservice_solution", Group: "knowledge", Title: "Knowledge base",
		Description: "Solution (knowledge base) categories, folders and articles. Articles live in folders, folders in categories.",
		Views: []View{
			{Action: "categories", Help: "solution categories.", Path: "/api/v2/solutions/categories", List: true, WS: WSAll},
			{Action: "category", Help: "solution category id.", Path: "/api/v2/solutions/categories/{id}"},
			{Action: "folders", Help: "folders of params.category_id.", Path: "/api/v2/solutions/folders", List: true},
			{Action: "folder", Help: "folder id.", Path: "/api/v2/solutions/folders/{id}"},
			{Action: "subfolders", Help: "sub-folders of folder id.", Path: "/api/v2/solutions/folders/{id}/sub-folders", List: true},
			{Action: "articles", Help: "articles of params.folder_id.", Path: "/api/v2/solutions/articles", List: true,
				Brief: []string{"id", "title", "status", "folder_id", "category_id", "approval_status", "views", "thumbs_up", "thumbs_down", "updated_at"}},
			{Action: "search", Help: "articles matching params.search_term; params user_email to search as that user.", Path: "/api/v2/solutions/articles/search", List: true,
				Brief: []string{"id", "title", "status", "folder_id", "category_id", "updated_at"}},
			{Action: "article", Help: "article id in full.", Path: "/api/v2/solutions/articles/{id}"},
		}},
	{Name: "freshservice_announcement", Group: "knowledge", Title: "Announcements",
		Description: "Announcements shown to agents and requesters.",
		Views: []View{
			{Action: "list", Help: "announcements; params state (active|archived|scheduled).", Path: "/api/v2/announcements", List: true, WS: WSAll},
			{Action: "get", Help: "announcement id.", Path: "/api/v2/announcements/{id}"},
		}},

	// catalog
	{Name: "freshservice_catalog", Group: "catalog", Title: "Service catalog",
		Description: "Service catalog categories and items requesters can order.",
		Views: []View{
			{Action: "categories", Help: "service catalog categories.", Path: "/api/v2/service_catalog/categories", List: true, WS: WSOne},
			{Action: "items", Help: "service catalog items; params category_id.", Path: "/api/v2/service_catalog/items", List: true, WS: WSOne,
				Brief: []string{"id", "display_id", "name", "short_description", "category_id", "visibility", "cost", "delivery_time", "workspace_id"}},
			{Action: "search", Help: "items matching params.search_term; params user_email.", Path: "/api/v2/service_catalog/items/search", List: true},
			{Action: "item", Help: "service catalog item id (display_id), with its custom fields.", Path: "/api/v2/service_catalog/items/{id}"},
			{Action: "shared_fields", Help: "shared catalog fields; params search.", Path: "/api/v2/service-catalog/shared-fields", List: true},
			{Action: "shared_field", Help: "shared catalog field id.", Path: "/api/v2/service-catalog/shared-fields/{id}"},
		}},
	{Name: "freshservice_onboarding", Group: "catalog", Title: "Employee onboarding and offboarding",
		Description: "Employee onboarding and offboarding requests and the tickets they spawned.",
		Views: []View{
			{Action: "onboarding_requests", Help: "onboarding requests.", Path: "/api/v2/onboarding_requests", List: true},
			{Action: "onboarding_request", Help: "onboarding request id.", Path: "/api/v2/onboarding_requests/{id}"},
			{Action: "onboarding_form", Help: "onboarding form fields.", Path: "/api/v2/onboarding_requests/form"},
			{Action: "onboarding_tickets", Help: "tickets of onboarding request id.", Path: "/api/v2/onboarding_requests/{id}/tickets"},
			{Action: "offboarding_requests", Help: "offboarding requests.", Path: "/api/v2/offboarding_requests", List: true},
			{Action: "offboarding_request", Help: "offboarding request id.", Path: "/api/v2/offboarding_requests/{id}"},
			{Action: "offboarding_form", Help: "offboarding form fields.", Path: "/api/v2/offboarding_requests/form"},
			{Action: "offboarding_tickets", Help: "tickets of offboarding request id.", Path: "/api/v2/offboarding_requests/{id}/tickets"},
		}},

	// projects
	{Name: "freshservice_project", Group: "projects", Title: "Projects",
		Description: "Projects and project tasks. Actions without a legacy_ prefix use new-gen project management (/pm); legacy_ actions use the legacy projects module.",
		Views: []View{
			{Action: "list", Help: "projects.", Path: "/api/v2/pm/projects", List: true},
			{Action: "get", Help: "project id.", Path: "/api/v2/pm/projects/{id}"},
			{Action: "fields", Help: "project fields.", Path: "/api/v2/pm/project-fields"},
			{Action: "templates", Help: "project templates.", Path: "/api/v2/pm/project_templates", List: true},
			{Action: "memberships", Help: "members of project id.", Path: "/api/v2/pm/projects/{id}/memberships", List: true},
			{Action: "sprints", Help: "sprints of project id.", Path: "/api/v2/pm/projects/{id}/sprints", List: true},
			{Action: "versions", Help: "versions of project id.", Path: "/api/v2/pm/projects/{id}/versions", List: true},
			{Action: "task_priorities", Help: "task priorities of project id.", Path: "/api/v2/pm/projects/{id}/task-priorities"},
			{Action: "task_statuses", Help: "task statuses of project id.", Path: "/api/v2/pm/projects/{id}/task-statuses"},
			{Action: "task_types", Help: "task types of project id.", Path: "/api/v2/pm/projects/{id}/task-types"},
			{Action: "task_type_fields", Help: "fields of task type params.task_type_id in project id.", Path: "/api/v2/pm/projects/{id}/task-types/{task_type_id}/fields"},
			{Action: "tasks", Help: "tasks of project id.", Path: "/api/v2/pm/projects/{id}/tasks", List: true},
			{Action: "tasks_filter", Help: "tasks of project id matching query.", Path: "/api/v2/pm/projects/{id}/tasks/filter", List: true, Filter: "query"},
			{Action: "task", Help: "task params.task_id of project id.", Path: "/api/v2/pm/projects/{id}/tasks/{task_id}"},
			{Action: "task_notes", Help: "notes of task params.task_id in project id.", Path: "/api/v2/pm/projects/{id}/tasks/{task_id}/notes", List: true},
			{Action: "task_associations", Help: "records of params.module (tickets, problems, changes, assets) linked to task params.task_id in project id.",
				Path: "/api/v2/pm/projects/{id}/tasks/{task_id}/{module}"},
			{Action: "associations", Help: "records of params.module (tickets, problems, changes, assets) linked to project id.", Path: "/api/v2/pm/projects/{id}/{module}"},
			{Action: "legacy_list", Help: "legacy projects.", Path: "/api/v2/projects", List: true},
			{Action: "legacy_get", Help: "legacy project id.", Path: "/api/v2/projects/{id}"},
			{Action: "legacy_tasks", Help: "tasks of legacy project id.", Path: "/api/v2/projects/{id}/tasks", List: true},
			{Action: "legacy_task", Help: "task params.task_id of legacy project id.", Path: "/api/v2/projects/{id}/tasks/{task_id}"},
		}},

	// ops
	{Name: "freshservice_statuspage", Group: "ops", Title: "Status pages",
		Description: "Freshservice status pages: their service components, subscribers, incidents and maintenances. " +
			"Incidents publish from tickets, maintenances from changes or maintenance windows; those actions take the ticket, change or window as id and the page as params.page_id.",
		Views: []View{
			{Action: "pages", Help: "status pages (every workspace).", Path: "/api/v2/status/pages", List: true},
			{Action: "components", Help: "service components of page id.", Path: "/api/v2/status/pages/{id}/service-components", List: true},
			{Action: "component", Help: "service component params.component_id of page id.", Path: "/api/v2/status/pages/{id}/service-components/{component_id}"},
			{Action: "subscribers", Help: "subscribers of page id.", Path: "/api/v2/status/pages/{id}/subscribers", List: true},
			{Action: "subscriber", Help: "subscriber params.subscriber_id of page id.", Path: "/api/v2/status/pages/{id}/subscribers/{subscriber_id}"},
			{Action: "incidents", Help: "incidents on page id.", Path: "/api/v2/status/pages/{id}/incidents", List: true},
			{Action: "incident_statuses", Help: "incident statuses of page id.", Path: "/api/v2/status/pages/{id}/incidents/statuses"},
			{Action: "maintenances", Help: "maintenances on page id.", Path: "/api/v2/status/pages/{id}/maintenances", List: true},
			{Action: "maintenance_statuses", Help: "maintenance statuses of page id.", Path: "/api/v2/status/pages/{id}/maintenances/statuses"},
			{Action: "ticket_incident", Help: "incident params.incident_id published from ticket id on params.page_id.", Path: "/api/v2/tickets/{id}/status/pages/{page_id}/incidents/{incident_id}"},
			{Action: "ticket_incident_updates", Help: "updates of incident params.incident_id from ticket id on params.page_id.",
				Path: "/api/v2/tickets/{id}/status/pages/{page_id}/incidents/{incident_id}/updates", List: true},
			{Action: "ticket_publishable_services", Help: "services ticket id can publish an incident for on params.page_id.", Path: "/api/v2/tickets/{id}/status/pages/{page_id}/publishable-services"},
			{Action: "change_maintenance", Help: "maintenance params.maintenance_id from change id on params.page_id.", Path: "/api/v2/changes/{id}/status/pages/{page_id}/maintenances/{maintenance_id}"},
			{Action: "change_maintenance_updates", Help: "updates of maintenance params.maintenance_id from change id on params.page_id.",
				Path: "/api/v2/changes/{id}/status/pages/{page_id}/maintenances/{maintenance_id}/updates", List: true},
			{Action: "change_publishable_services", Help: "services change id can publish a maintenance for on params.page_id.", Path: "/api/v2/changes/{id}/status/pages/{page_id}/publishable-services"},
			{Action: "window_maintenance", Help: "maintenance params.maintenance_id from maintenance window id on params.page_id.",
				Path: "/api/v2/maintenance-windows/{id}/status/pages/{page_id}/maintenances/{maintenance_id}"},
			{Action: "window_maintenance_updates", Help: "updates of maintenance params.maintenance_id from maintenance window id on params.page_id.",
				Path: "/api/v2/maintenance-windows/{id}/status/pages/{page_id}/maintenances/{maintenance_id}/updates", List: true},
			{Action: "window_publishable_services", Help: "services maintenance window id can publish for on params.page_id.",
				Path: "/api/v2/maintenance-windows/{id}/status/pages/{page_id}/publishable-services"},
		}},
	{Name: "freshservice_oncall", Group: "ops", Title: "On-call schedules",
		Description: "On-call schedules, shifts and escalation policies, and who is on call now. Schedules belong to one workspace.",
		Views: []View{
			{Action: "now", Help: "who is on call now; params schedule_id.", Path: "/api/v2/oncall/shift-events/current"},
			{Action: "events", Help: "calendar events of a schedule; params schedule_id, start_time, end_time.", Path: "/api/v2/oncall/shift-events"},
			{Action: "schedules", Help: "on-call schedules of a workspace; params name to filter.", Path: "/api/v2/oncall/ws/{workspace_id}/schedules", List: true, WS: WSOne},
			{Action: "schedule", Help: "schedule id.", Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}", WS: WSOne},
			{Action: "shifts", Help: "shifts of schedule id.", Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}/shifts", List: true, WS: WSOne},
			{Action: "shift", Help: "shift params.shift_id of schedule id.", Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}/shifts/{shift_id}", WS: WSOne},
			{Action: "escalation_policies", Help: "escalation policies of schedule id.", Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}/escalation-policies", List: true, WS: WSOne},
			{Action: "escalation_policy", Help: "escalation policy params.policy_id of schedule id.",
				Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}/escalation-policies/{policy_id}", WS: WSOne},
		}},
	{Name: "freshservice_alert", Group: "ops", Title: "Alerts",
		Description: "Alert Management (monitoring alerts routed into Freshservice), with notes and logs.",
		Views: []View{
			{Action: "list", Help: "alerts; params state, severity, alert_type, resource, created_since.", Path: "/api/v2/ams/alerts", List: true},
			{Action: "get", Help: "alert id.", Path: "/api/v2/ams/alerts/{id}"},
			{Action: "logs", Help: "log of alert id; params start_token for the next batch.", Path: "/api/v2/ams/alerts/{id}/logs"},
			{Action: "notes", Help: "notes of alert id.", Path: "/api/v2/ams/alerts/{id}/notes", List: true},
			{Action: "note", Help: "note params.note_id of alert id.", Path: "/api/v2/ams/alerts/{id}/notes/{note_id}"},
		}},
	{Name: "freshservice_journey", Group: "ops", Title: "Journeys",
		Description: "Journeys (multi-step employee workflows such as role changes) and their requests.",
		Views: []View{
			{Action: "configs", Help: "published journey configurations.", Path: "/api/v2/journeys/configs", List: true},
			{Action: "config_fields", Help: "initiator form fields of journey config id.", Path: "/api/v2/journeys/configs/{id}/data-fields"},
			{Action: "requests", Help: "journey requests.", Path: "/api/v2/journeys/requests", List: true},
			{Action: "request", Help: "journey request id.", Path: "/api/v2/journeys/requests/{id}"},
			{Action: "request_activities", Help: "activities of journey request id.", Path: "/api/v2/journeys/requests/{id}/activities", List: true},
		}},

	// custom
	{Name: "freshservice_custom_object", Group: "custom", Title: "Custom objects",
		Description: "Custom objects defined in this Freshservice account, and their records. Record fields are tenant-defined: get the object first to see them.",
		Views: []View{
			{Action: "objects", Help: "custom objects.", Path: "/api/v2/objects", List: true, WS: WSOne},
			{Action: "object", Help: "custom object id, with its field definitions.", Path: "/api/v2/objects/{id}"},
			{Action: "records", Help: "records of custom object id; params query (custom-object syntax), sort_field, order_by.", Path: "/api/v2/objects/{id}/records", List: true},
		}},
}
