package tools

// writeViews are appended to the read tools they act on. Each names its
// capability (docs/adr/0002-capability-map.md); deletes never appear here.
var writeViews = map[string][]View{
	"freshservice_ticket": {
		// tickets
		{Action: "create", Help: "create a ticket in workspace; body {subject, description, email or requester_id, status, priority, type, group_id, responder_id, category, custom_fields, assets: [{display_id}]}.",
			Method: "POST", Path: "/api/v2/tickets", Capability: "tickets", Body: true, Require: []string{"status", "priority"}, Create: true, WS: WSOne},
		{Action: "update", Help: "change ticket id; body holds only the fields to change. Sending assets REPLACES every linked asset, so it also needs confirm = the ticket's subject.",
			Method: "PUT", Path: "/api/v2/tickets/{id}", Capability: "tickets", Body: true, Confirm: "subject", ConfirmIf: "assets", ConfirmPath: "/api/v2/tickets/{id}"},
		{Action: "create_child", Help: "create a child ticket under ticket id; body as create.", Method: "POST", Path: "/api/v2/tickets/{id}/create_child_ticket", Capability: "tickets", Body: true},
		{Action: "note", Help: "add a note to ticket id; body {body (HTML), private (default true), notify_emails}.", Method: "POST", Path: "/api/v2/tickets/{id}/notes",
			Capability: "tickets", Body: true, Require: []string{"body"}},
		{Action: "update_conversation", Help: "edit conversation (note or reply) id; body {body}.", Method: "PUT", Path: "/api/v2/conversations/{id}", Capability: "tickets", Body: true},
		{Action: "create_task", Help: "add a task to ticket id; body {title, description, status, due_date, notify_before, agent_id, group_id}.", Method: "POST",
			Path: "/api/v2/tickets/{id}/tasks", Capability: "tickets", Body: true, Require: []string{"title"}},
		{Action: "update_task", Help: "change task params.task_id of ticket id.", Method: "PUT", Path: "/api/v2/tickets/{id}/tasks/{task_id}", Capability: "tickets", Body: true},
		{Action: "create_time_entry", Help: "log time on ticket id; body {agent_id, time_spent (hh:mm), billable, executed_at, note, task_id}.", Method: "POST",
			Path: "/api/v2/tickets/{id}/time_entries", Capability: "tickets", Body: true, Require: []string{"agent_id"}},
		{Action: "update_time_entry", Help: "change time entry params.time_entry_id of ticket id.", Method: "PUT", Path: "/api/v2/tickets/{id}/time_entries/{time_entry_id}", Capability: "tickets", Body: true},
		{Action: "request_approval", Help: "ask for approval on service request id; body {approver_id, approval_type, email_content}.", Method: "POST",
			Path: "/api/v2/tickets/{id}/approvals", Capability: "tickets", Body: true},
		{Action: "create_approval_groups", Help: "add approval groups to service request id; body as Freshservice documents.", Method: "POST",
			Path: "/api/v2/tickets/{id}/approval-groups", Capability: "tickets", Body: true},
		{Action: "update_approval_chain", Help: "change the approval chain rule of service request id; body {approval_chain_type}.", Method: "PUT",
			Path: "/api/v2/tickets/{id}/approval-chain-rule", Capability: "tickets", Body: true},
		{Action: "cancel_approval", Help: "cancel approval params.approval_id of ticket id.", Method: "PUT", Path: "/api/v2/tickets/{id}/approvals/{approval_id}", Capability: "tickets"},
		{Action: "cancel_approval_group", Help: "cancel approval group params.group_id of service request id.", Method: "PUT",
			Path: "/api/v2/tickets/{id}/approval-groups/{group_id}", Capability: "tickets"},
		{Action: "remind_approval", Help: "remind the approver of approval params.approval_id of ticket id.", Method: "PUT",
			Path: "/api/v2/tickets/{id}/approvals/{approval_id}/remind", Capability: "tickets"},
		{Action: "add_requested_item", Help: "add a catalog item to service request id; body {service_item_id, quantity, custom_fields}.", Method: "POST",
			Path: "/api/v2/tickets/{id}/requested_items", Capability: "tickets", Body: true},
		{Action: "update_requested_item", Help: "change requested item params.item_id of service request id.", Method: "PUT",
			Path: "/api/v2/tickets/{id}/requested_items/{item_id}", Capability: "tickets", Body: true},
		{Action: "move_workspace", Help: "move ticket id to another workspace; body {workspace_id, group_id, responder_id}. confirm = the ticket's subject.", Method: "PUT",
			Path: "/api/v2/tickets/{id}/move_workspace", Capability: "tickets", Body: true, Require: []string{"workspace_id"}, Confirm: "subject", ConfirmPath: "/api/v2/tickets/{id}"},
		{Action: "restore", Help: "restore deleted ticket id from trash.", Method: "PUT", Path: "/api/v2/tickets/{id}/restore", Capability: "tickets"},
		// ticket-replies: these email the requester or a third party
		{Action: "reply", Help: "reply to ticket id; emails the requester. body {body (HTML), cc_emails, bcc_emails}.", Method: "POST", Path: "/api/v2/tickets/{id}/reply",
			Capability: "ticket-replies", Body: true, Require: []string{"body"}},
		{Action: "send_email", Help: "start an email or Zoom collaboration from ticket id; emails people outside the ticket. body as Freshservice documents.", Method: "POST",
			Path: "/api/v2/tickets/{id}/communications", Capability: "ticket-replies", Body: true},
		// itil: major incidents
		{Action: "promote_major", Help: "promote incident id to a major incident; body {major_incident_type, ...}.", Method: "PUT", Path: "/api/v2/tickets/{id}/promote", Capability: "itil", Body: true},
		{Action: "demote_major", Help: "demote major incident id back to an incident.", Method: "PUT", Path: "/api/v2/tickets/{id}/demote", Capability: "itil", Body: true},
	},
	"freshservice_catalog": {
		{Action: "place_request", Help: "order catalog item id (display_id), creating a service request; body {email or requested_for, quantity, custom_fields}.", Method: "POST",
			Path: "/api/v2/service_catalog/items/{id}/place_request", Capability: "tickets", Body: true},
	},
	"freshservice_requester": {
		{Action: "create", Help: "create a requester; body {first_name, last_name, primary_email, job_title, department_ids, location_id, reporting_manager_id, custom_fields}.", Method: "POST",
			Path: "/api/v2/requesters", Capability: "people", Body: true, Require: []string{"first_name"}},
		{Action: "update", Help: "change requester id.", Method: "PUT", Path: "/api/v2/requesters/{id}", Capability: "people", Body: true},
		{Action: "merge", Help: "merge params.secondary_requesters (comma-separated ids) into requester id; the secondaries' tickets move and they are removed. confirm = the primary's primary_email.",
			Method: "PUT", Path: "/api/v2/requesters/{id}/merge", Capability: "people", Confirm: "primary_email", ConfirmPath: "/api/v2/requesters/{id}", Destructive: true},
		{Action: "reactivate", Help: "reactivate deactivated requester id.", Method: "PUT", Path: "/api/v2/requesters/{id}/reactivate", Capability: "people"},
		{Action: "create_group", Help: "create a requester group; body {name, description}.", Method: "POST", Path: "/api/v2/requester_groups", Capability: "people", Body: true, Require: []string{"name"}},
		{Action: "update_group", Help: "change requester group id.", Method: "PUT", Path: "/api/v2/requester_groups/{id}", Capability: "people", Body: true},
		{Action: "add_group_member", Help: "add requester params.requester_id to requester group id.", Method: "POST",
			Path: "/api/v2/requester_groups/{id}/members/{requester_id}", Capability: "people"},
		{Action: "remove_group_member", Help: "remove requester params.requester_id from requester group id (the requester is kept).", Method: "DELETE",
			Path: "/api/v2/requester_groups/{id}/members/{requester_id}", Capability: "people"},
	},
	"freshservice_lookup": {
		{Action: "create_department", Help: "create a department; body {name, description, head_user_id, prime_user_id, domains, custom_fields}.", Method: "POST",
			Path: "/api/v2/departments", Capability: "people", Body: true, Require: []string{"name"}},
		{Action: "update_department", Help: "change department id.", Method: "PUT", Path: "/api/v2/departments/{id}", Capability: "people", Body: true},
		{Action: "create_location", Help: "create a location; body {name, parent_location_id, primary_contact_id, address}.", Method: "POST",
			Path: "/api/v2/locations", Capability: "people", Body: true, Require: []string{"name"}},
		{Action: "update_location", Help: "change location id.", Method: "PUT", Path: "/api/v2/locations/{id}", Capability: "people", Body: true},
	},
	"freshservice_onboarding": {
		{Action: "create_onboarding", Help: "start an onboarding request; body {fields: {...}} per onboarding_form. Kicks off HR and IT workflows.", Method: "POST",
			Path: "/api/v2/onboarding_requests", Capability: "people", Body: true},
		{Action: "create_offboarding", Help: "start an offboarding request; body {fields: {...}} per offboarding_form. Kicks off HR and IT workflows.", Method: "POST",
			Path: "/api/v2/offboarding_requests", Capability: "people", Body: true},
	},
}
