package tools

// itilWrites are the writes problems, changes and releases share.
func itilWrites(base, name string) []View {
	rec := base + "/{id}"
	return []View{
		{Action: "create", Help: "create a " + name + " in workspace; body {subject, description, requester_id, status, priority, impact, agent_id, group_id, planned_start_date, planned_end_date, custom_fields, ...}.",
			Method: "POST", Path: base, Capability: "itil", Body: true, Create: true, WS: WSOne},
		{Action: "update", Help: "change " + name + " id; body holds only the fields to change.", Method: "PUT", Path: rec, Capability: "itil", Body: true},
		{Action: "move_workspace", Help: "move " + name + " id to another workspace; body {workspace_id, group_id, agent_id}. confirm = its subject.", Method: "PUT",
			Path: rec + "/move_workspace", Capability: "itil", Body: true, Require: []string{"workspace_id"}, Confirm: "subject", ConfirmPath: rec},
		{Action: "create_note", Help: "add a note to " + name + " id; body {body, notify_emails}.", Method: "POST", Path: rec + "/notes", Capability: "itil", Body: true, Require: []string{"body"}},
		{Action: "update_note", Help: "change note params.note_id of " + name + " id.", Method: "PUT", Path: rec + "/notes/{note_id}", Capability: "itil", Body: true},
		{Action: "create_task", Help: "add a task to " + name + " id; body {title, description, status, due_date, agent_id, group_id}.", Method: "POST",
			Path: rec + "/tasks", Capability: "itil", Body: true, Require: []string{"title"}},
		{Action: "update_task", Help: "change task params.task_id of " + name + " id.", Method: "PUT", Path: rec + "/tasks/{task_id}", Capability: "itil", Body: true},
		{Action: "create_time_entry", Help: "log time on " + name + " id; body {agent_id, time_spent (hh:mm), billable, executed_at, note}.", Method: "POST",
			Path: rec + "/time_entries", Capability: "itil", Body: true, Require: []string{"agent_id"}},
		{Action: "update_time_entry", Help: "change time entry params.time_entry_id of " + name + " id.", Method: "PUT", Path: rec + "/time_entries/{time_entry_id}", Capability: "itil", Body: true},
	}
}

// statusPublish is a status page write: it is public, so confirm names the
// ticket or change it publishes from.
func statusPublish(action, help, method, path, record string) View {
	return View{Action: action, Help: help + " Public: confirm = the " + record + "'s subject.", Method: method, Path: path, Capability: "ops", Body: true,
		Confirm: "subject", ConfirmPath: "/api/v2/" + record + "s/{id}", Destructive: true}
}

var moreWrites = map[string][]View{
	"freshservice_problem": append(itilWrites("/api/v2/problems", "problem"),
		View{Action: "restore", Help: "restore deleted problem id from trash.", Method: "PUT", Path: "/api/v2/problems/{id}/restore", Capability: "itil"}),
	"freshservice_change": append(itilWrites("/api/v2/changes", "change"),
		View{Action: "create_approval_groups", Help: "add approval groups to change id.", Method: "POST", Path: "/api/v2/changes/{id}/approval-groups", Capability: "itil", Body: true},
		View{Action: "update_approval_chain", Help: "change the approval chain rule of change id; body {approval_chain_type}.", Method: "PUT",
			Path: "/api/v2/changes/{id}/approval-chain-rule", Capability: "itil", Body: true},
		View{Action: "cancel_approval", Help: "cancel approval params.approval_id of change id.", Method: "PUT", Path: "/api/v2/changes/{id}/approvals/{approval_id}", Capability: "itil"},
		View{Action: "cancel_approval_group", Help: "cancel approval group params.group_id of change id.", Method: "PUT",
			Path: "/api/v2/changes/{id}/approval-groups/{group_id}", Capability: "itil"},
		View{Action: "remind_approval", Help: "remind the approver of approval params.approval_id of change id.", Method: "PUT",
			Path: "/api/v2/changes/{id}/approvals/{approval_id}/remind", Capability: "itil"},
		View{Action: "create_cab", Help: "create a Change Advisory Board; body {name, description, members}.", Method: "POST", Path: "/api/v2/cabs", Capability: "itil", Body: true, Require: []string{"name"}},
		View{Action: "update_cab", Help: "change CAB id.", Method: "PATCH", Path: "/api/v2/cabs/{id}", Capability: "itil", Body: true},
	),
	"freshservice_release": append(itilWrites("/api/v2/releases", "release"),
		View{Action: "restore", Help: "restore deleted release id from trash.", Method: "PUT", Path: "/api/v2/releases/{id}/restore", Capability: "itil"},
		View{Action: "create_pir_template", Help: "create a post-incident report template.", Method: "POST", Path: "/api/v2/post-incident-reports/templates", Capability: "itil", Body: true},
		View{Action: "update_pir_template", Help: "enable or change post-incident report template id.", Method: "PUT", Path: "/api/v2/post-incident-reports/templates/{id}", Capability: "itil", Body: true},
		View{Action: "primary_pir_template", Help: "make post-incident report template id the primary one.", Method: "PUT",
			Path: "/api/v2/post-incident-reports/templates/{id}/mark-as-primary", Capability: "itil"},
	),

	"freshservice_asset": {
		{Action: "create", Help: "create an asset in workspace; body {name, asset_type_id, asset_tag, impact, usage_type, user_id, department_id, location_id, type_fields: {...}}.",
			Method: "POST", Path: "{assets}", Capability: "assets", Body: true, Require: []string{"name", "asset_type_id"}, Create: true, WS: WSOne},
		{Action: "update", Help: "change asset id; body holds only the fields to change.", Method: "PUT", Path: "{assets}/{id}", Capability: "assets", Body: true},
		{Action: "bulk_update", Help: "ITAM only: update several assets; body as Freshservice documents.", Method: "PUT", Path: "/api/v2/itam/assets", Capability: "assets", Body: true},
		{Action: "move_workspace", Help: "move asset id to another workspace; body {workspace_id, group_id, agent_id}. confirm = the asset's name.", Method: "PUT",
			Path: "/api/v2/assets/{id}/move_workspace", Capability: "assets", Body: true, Require: []string{"workspace_id"}, Confirm: "name", ConfirmPath: "/api/v2/assets/{id}"},
		{Action: "restore", Help: "restore deleted asset id from trash.", Method: "PUT", Path: "/api/v2/assets/{id}/restore", Capability: "assets"},
		{Action: "create_component", Help: "add a hardware component to asset id; body {component_type, component_data}.", Method: "POST",
			Path: "/api/v2/assets/{id}/components", Capability: "assets", Body: true},
		{Action: "update_component", Help: "change component params.component_id of asset id.", Method: "PUT", Path: "/api/v2/assets/{id}/components/{component_id}", Capability: "assets", Body: true},
		{Action: "create_relationships", Help: "create CMDB relationships in bulk; body {relationships: [{relationship_type_id, primary_id, primary_type, secondary_id, secondary_type}]}.",
			Method: "POST", Path: "/api/v2/relationships/bulk-create", Capability: "assets", Body: true, Require: []string{"relationships"}},
		{Action: "create_type", Help: "create an asset type; body {name, parent_asset_type_id, description}.", Method: "POST", Path: "/api/v2/asset_types", Capability: "assets", Body: true, Require: []string{"name"}},
		{Action: "update_type", Help: "change asset type id.", Method: "PUT", Path: "/api/v2/asset_types/{id}", Capability: "assets", Body: true},
		{Action: "create_device", Help: "ITAM: create a device.", Method: "POST", Path: "/api/v2/itam/devices", Capability: "assets", Body: true},
		{Action: "update_device", Help: "ITAM: change device id.", Method: "PUT", Path: "/api/v2/itam/devices/{id}", Capability: "assets", Body: true},
		{Action: "upsert_physical_subtypes", Help: "ITAM: create or update physical subtypes.", Method: "POST", Path: "/api/v2/itam/physical-subtypes", Capability: "assets", Body: true},
		{Action: "upsert_lifecycle_events", Help: "ITAM: create or update lifecycle events.", Method: "PUT", Path: "/api/v2/itam/lifecycle_events", Capability: "assets", Body: true},
		{Action: "update_cloud_infrastructures", Help: "ITAM: update cloud infrastructure details.", Method: "POST", Path: "/api/v2/itam/cloud_infrastructures", Capability: "assets", Body: true},
		{Action: "update_cloud_resources", Help: "ITAM: update cloud resources.", Method: "POST", Path: "/api/v2/itam/resources", Capability: "assets", Body: true},
	},
	"freshservice_software": {
		{Action: "create", Help: "create a software application in workspace; body {name, application_type, status, category, publisher_id, managed_by_id, notes}.",
			Method: "POST", Path: "/api/v2/applications", Capability: "assets", Body: true, Require: []string{"name"}, Create: true, WS: WSOne},
		{Action: "update", Help: "change software id.", Method: "PUT", Path: "/api/v2/applications/{id}", Capability: "assets", Body: true},
		{Action: "move_workspace", Help: "move software id to another workspace; body {workspace_id}. confirm = its name.", Method: "PUT",
			Path: "/api/v2/applications/{id}/move_workspace", Capability: "assets", Body: true, Require: []string{"workspace_id"}, Confirm: "name", ConfirmPath: "/api/v2/applications/{id}"},
		{Action: "add_installation", Help: "record software id as installed on a device; body {installation_machine_id, installation_path, version, installation_date}.", Method: "POST",
			Path: "/api/v2/applications/{id}/installations", Capability: "assets", Body: true},
		{Action: "remove_installations", Help: "unlink devices from software id; params device_ids (comma-separated). The devices are kept.", Method: "DELETE",
			Path: "/api/v2/applications/{id}/installations", Capability: "assets"},
		{Action: "add_users", Help: "add users to software id; body {application_users: [{user_id, license_id, allocated_date}]}.", Method: "POST",
			Path: "/api/v2/applications/{id}/users", Capability: "assets", Body: true},
		{Action: "update_users", Help: "change users of software id; body {application_users: [...]}.", Method: "PUT", Path: "/api/v2/applications/{id}/users", Capability: "assets", Body: true},
		{Action: "remove_users", Help: "unlink users from software id; params user_ids (comma-separated). The users are kept.", Method: "DELETE",
			Path: "/api/v2/applications/{id}/users", Capability: "assets"},
	},
	"freshservice_contract": {
		{Action: "create", Help: "create a contract in workspace; body {name, contract_number, contract_type_id, vendor_id, approver_id, cost, start_date, end_date, ...}.",
			Method: "POST", Path: "/api/v2/contracts", Capability: "assets", Body: true, Create: true, WS: WSOne},
		{Action: "update", Help: "change contract id.", Method: "PUT", Path: "/api/v2/contracts/{id}", Capability: "assets", Body: true},
		{Action: "move_workspace", Help: "move contract id to another workspace; body {workspace_id}. confirm = its name.", Method: "PUT",
			Path: "/api/v2/contracts/{id}/move_workspace", Capability: "assets", Body: true, Require: []string{"workspace_id"}, Confirm: "name", ConfirmPath: "/api/v2/contracts/{id}"},
		{Action: "approve", Help: "approve contract id as the API key's agent. confirm = the contract's name.", Method: "PUT", Path: "/api/v2/contracts/{id}",
			Defaults: map[string]string{"operation": "approve"}, Capability: "approvals", Confirm: "name", ConfirmPath: "/api/v2/contracts/{id}"},
		{Action: "reject", Help: "reject contract id as the API key's agent; body {comments}. confirm = the contract's name.", Method: "PUT", Path: "/api/v2/contracts/{id}",
			Defaults: map[string]string{"operation": "reject"}, Capability: "approvals", Body: true, Confirm: "name", ConfirmPath: "/api/v2/contracts/{id}"},
	},
	"freshservice_procurement": {
		{Action: "create_vendor", Help: "create a vendor; body {name, description, contact_name, email, phone, address}.", Method: "POST", Path: "/api/v2/vendors", Capability: "assets", Body: true, Require: []string{"name"}},
		{Action: "update_vendor", Help: "change vendor id.", Method: "PUT", Path: "/api/v2/vendors/{id}", Capability: "assets", Body: true},
		{Action: "create_product", Help: "create a product; body {name, asset_type_id, manufacturer, status, mode_of_procurement, depreciation_type_id}.", Method: "POST",
			Path: "/api/v2/products", Capability: "assets", Body: true, Require: []string{"name", "asset_type_id"}},
		{Action: "update_product", Help: "change product id.", Method: "PUT", Path: "/api/v2/products/{id}", Capability: "assets", Body: true},
		{Action: "create_purchase_order", Help: "create a purchase order in workspace; body {vendor_id, name, po_number, expected_delivery_date, purchase_items: [...]}.",
			Method: "POST", Path: "/api/v2/purchase_orders", Capability: "assets", Body: true, Create: true, WS: WSOne},
		{Action: "update_purchase_order", Help: "change purchase order id.", Method: "PUT", Path: "/api/v2/purchase_orders/{id}", Capability: "assets", Body: true},
		{Action: "move_purchase_order", Help: "move purchase order id to another workspace; body {workspace_id}. confirm = its name.", Method: "PUT",
			Path: "/api/v2/purchase_orders/{id}/move_workspace", Capability: "assets", Body: true, Require: []string{"workspace_id"}, Confirm: "name", ConfirmPath: "/api/v2/purchase_orders/{id}"},
	},

	"freshservice_solution": {
		{Action: "create_category", Help: "create a solution category in workspace; body {name, description, visible_in_portals}.", Method: "POST",
			Path: "/api/v2/solutions/categories", Capability: "knowledge", Body: true, Require: []string{"name"}, Create: true, WS: WSOne},
		{Action: "update_category", Help: "change solution category id.", Method: "PUT", Path: "/api/v2/solutions/categories/{id}", Capability: "knowledge", Body: true},
		{Action: "restore_category", Help: "restore deleted solution category id.", Method: "PUT", Path: "/api/v2/solutions/categories/{id}/restore", Capability: "knowledge"},
		{Action: "create_folder", Help: "create a folder; body {name, category_id, visibility, description, parent_id}.", Method: "POST", Path: "/api/v2/solutions/folders",
			Capability: "knowledge", Body: true, Require: []string{"name", "category_id"}},
		{Action: "update_folder", Help: "change folder id.", Method: "PUT", Path: "/api/v2/solutions/folders/{id}", Capability: "knowledge", Body: true},
		{Action: "restore_folder", Help: "restore deleted folder id.", Method: "PUT", Path: "/api/v2/solutions/folders/{id}/restore", Capability: "knowledge"},
		{Action: "create_article", Help: "create an article; body {title, description (HTML), folder_id, article_type (1 permanent, 2 workaround), status (1 draft, 2 published), tags, keywords, review_date}.",
			Method: "POST", Path: "/api/v2/solutions/articles", Capability: "knowledge", Body: true, Require: []string{"title", "description", "folder_id"}},
		{Action: "update_article", Help: "change or publish article id (status 2 publishes).", Method: "PUT", Path: "/api/v2/solutions/articles/{id}", Capability: "knowledge", Body: true},
		{Action: "send_for_approval", Help: "send article id for approval; body {approver_id}.", Method: "PUT", Path: "/api/v2/solutions/articles/{id}/send_for_approval", Capability: "knowledge", Body: true},
		{Action: "restore_article", Help: "restore deleted article id.", Method: "PUT", Path: "/api/v2/solutions/articles/{id}/restore", Capability: "knowledge"},
		{Action: "restore_articles", Help: "restore several deleted articles; body {article_ids: [...]}.", Method: "PUT", Path: "/api/v2/solutions/articles/bulk_restore",
			Capability: "knowledge", Body: true, Require: []string{"article_ids"}},
	},
	"freshservice_announcement": {
		{Action: "create", Help: "create an announcement in workspace; body {title, body_html, visible_from, visible_till, visibility, departments, groups, is_read}.",
			Method: "POST", Path: "/api/v2/announcements", Capability: "knowledge", Body: true, Require: []string{"title", "body_html"}, Create: true, WS: WSOne},
		{Action: "update", Help: "change announcement id.", Method: "PUT", Path: "/api/v2/announcements/{id}", Capability: "knowledge", Body: true},
	},

	"freshservice_project": {
		{Action: "create", Help: "create a project; body {name, key, description, start_date, end_date, manager_id, template_id, ...}.", Method: "POST", Path: "/api/v2/pm/projects",
			Capability: "projects", Body: true, Require: []string{"name"}},
		{Action: "update", Help: "change project id.", Method: "PUT", Path: "/api/v2/pm/projects/{id}", Capability: "projects", Body: true},
		{Action: "archive", Help: "archive project id.", Method: "POST", Path: "/api/v2/pm/projects/{id}/archive", Capability: "projects"},
		{Action: "restore", Help: "restore archived project id.", Method: "POST", Path: "/api/v2/pm/projects/{id}/restore", Capability: "projects"},
		{Action: "add_members", Help: "add members to project id; body {members: [{user_id, role}]}.", Method: "POST", Path: "/api/v2/pm/projects/{id}/members", Capability: "projects", Body: true},
		{Action: "associate", Help: "link records of params.module (tickets, problems, changes, assets) to project id; body {ids: [...]}.", Method: "POST",
			Path: "/api/v2/pm/projects/{id}/{module}", Capability: "projects", Body: true},
		{Action: "create_task", Help: "add a task to project id; body {title, description, type_id, status_id, priority_id, assignee_id, start_date, due_date, parent_id}.", Method: "POST",
			Path: "/api/v2/pm/projects/{id}/tasks", Capability: "projects", Body: true, Require: []string{"title"}},
		{Action: "update_task", Help: "change task params.task_id of project id.", Method: "PUT", Path: "/api/v2/pm/projects/{id}/tasks/{task_id}", Capability: "projects", Body: true},
		{Action: "create_task_note", Help: "add a note to task params.task_id of project id; body {content}.", Method: "POST",
			Path: "/api/v2/pm/projects/{id}/tasks/{task_id}/notes", Capability: "projects", Body: true},
		{Action: "update_task_note", Help: "change note params.note_id on task params.task_id of project id.", Method: "PUT",
			Path: "/api/v2/pm/projects/{id}/tasks/{task_id}/notes/{note_id}", Capability: "projects", Body: true},
		{Action: "associate_task", Help: "link records of params.module to task params.task_id of project id; body {ids: [...]}.", Method: "POST",
			Path: "/api/v2/pm/projects/{id}/tasks/{task_id}/{module}", Capability: "projects", Body: true},
		{Action: "legacy_create", Help: "create a legacy project.", Method: "POST", Path: "/api/v2/projects", Capability: "projects", Body: true, Require: []string{"name"}},
		{Action: "legacy_update", Help: "change legacy project id.", Method: "PUT", Path: "/api/v2/projects/{id}", Capability: "projects", Body: true},
		{Action: "legacy_archive", Help: "archive legacy project id.", Method: "POST", Path: "/api/v2/projects/{id}/archive", Capability: "projects"},
		{Action: "legacy_restore", Help: "restore archived legacy project id.", Method: "POST", Path: "/api/v2/projects/{id}/restore", Capability: "projects"},
		{Action: "legacy_create_task", Help: "add a task to legacy project id.", Method: "POST", Path: "/api/v2/projects/{id}/tasks", Capability: "projects", Body: true},
		{Action: "legacy_update_task", Help: "change task params.task_id of legacy project id.", Method: "PUT", Path: "/api/v2/projects/{id}/tasks/{task_id}", Capability: "projects", Body: true},
	},

	"freshservice_statuspage": {
		{Action: "create_subscriber", Help: "subscribe someone to page id; body {email, service_component_ids}.", Method: "POST", Path: "/api/v2/status/pages/{id}/subscribers",
			Capability: "ops", Body: true, Require: []string{"email"}},
		{Action: "update_subscriber", Help: "change subscriber params.subscriber_id of page id.", Method: "PUT", Path: "/api/v2/status/pages/{id}/subscribers/{subscriber_id}", Capability: "ops", Body: true},
		statusPublish("publish_incident", "publish an incident from ticket id on params.page_id; body {title, description, status, impacted_services, notify_subscribers}.",
			"POST", "/api/v2/tickets/{id}/status/pages/{page_id}/incidents", "ticket"),
		statusPublish("update_incident", "change incident params.incident_id from ticket id on params.page_id.",
			"PUT", "/api/v2/tickets/{id}/status/pages/{page_id}/incidents/{incident_id}", "ticket"),
		statusPublish("post_incident_update", "post an update to incident params.incident_id from ticket id on params.page_id; body {body, status, notify_subscribers}.",
			"POST", "/api/v2/tickets/{id}/status/pages/{page_id}/incidents/{incident_id}/updates", "ticket"),
		statusPublish("edit_incident_update", "edit update params.update_id of incident params.incident_id from ticket id on params.page_id.",
			"PUT", "/api/v2/tickets/{id}/status/pages/{page_id}/incidents/{incident_id}/updates/{update_id}", "ticket"),
		statusPublish("publish_maintenance", "publish a maintenance from change id on params.page_id; body {title, description, started_at, ended_at, impacted_services, notify_subscribers}.",
			"POST", "/api/v2/changes/{id}/status/pages/{page_id}/maintenances", "change"),
		statusPublish("update_maintenance", "change maintenance params.maintenance_id from change id on params.page_id.",
			"PUT", "/api/v2/changes/{id}/status/pages/{page_id}/maintenances/{maintenance_id}", "change"),
		statusPublish("post_maintenance_update", "post an update to maintenance params.maintenance_id from change id on params.page_id.",
			"POST", "/api/v2/changes/{id}/status/pages/{page_id}/maintenances/{maintenance_id}/updates", "change"),
		statusPublish("edit_maintenance_update", "edit update params.update_id of maintenance params.maintenance_id from change id on params.page_id.",
			"PUT", "/api/v2/changes/{id}/status/pages/{page_id}/maintenances/{maintenance_id}/updates/{update_id}", "change"),
	},
	"freshservice_oncall": {
		{Action: "create_schedule", Help: "create an on-call schedule in the workspace; body {name, description, time_zone, members}.", Method: "POST",
			Path: "/api/v2/oncall/ws/{workspace_id}/schedules", Capability: "ops", Body: true, Require: []string{"name"}, WS: WSOne},
		{Action: "update_schedule", Help: "change schedule id.", Method: "PUT", Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}", Capability: "ops", Body: true, WS: WSOne},
		{Action: "create_shift", Help: "add a shift to schedule id.", Method: "POST", Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}/shifts", Capability: "ops", Body: true, WS: WSOne},
		{Action: "update_shift", Help: "change shift params.shift_id of schedule id.", Method: "PUT",
			Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}/shifts/{shift_id}", Capability: "ops", Body: true, WS: WSOne},
		{Action: "create_escalation_policy", Help: "add an escalation policy to schedule id.", Method: "POST",
			Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}/escalation-policies", Capability: "ops", Body: true, WS: WSOne},
		{Action: "update_escalation_policy", Help: "change escalation policy params.policy_id of schedule id.", Method: "PUT",
			Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}/escalation-policies/{policy_id}", Capability: "ops", Body: true, WS: WSOne},
		{Action: "reorder_escalation_policies", Help: "reorder the escalation policies of schedule id; body {escalation_policy_ids: [...]}.", Method: "PUT",
			Path: "/api/v2/oncall/ws/{workspace_id}/schedules/{id}/escalation-policies/reorder", Capability: "ops", Body: true, WS: WSOne},
	},
	"freshservice_alert": {
		{Action: "acknowledge", Help: "acknowledge alert id.", Method: "PUT", Path: "/api/v2/ams/alerts/{id}/acknowledge", Capability: "ops"},
		{Action: "resolve", Help: "resolve alert id.", Method: "PUT", Path: "/api/v2/ams/alerts/{id}/resolve", Capability: "ops"},
		{Action: "suppress", Help: "suppress alert id; body {suppress_until}.", Method: "PUT", Path: "/api/v2/ams/alerts/{id}/suppress", Capability: "ops", Body: true},
		{Action: "unsuppress", Help: "stop suppressing alert id.", Method: "PUT", Path: "/api/v2/ams/alerts/{id}/unsuppress", Capability: "ops"},
		{Action: "create_note", Help: "add a note to alert id; body {content}.", Method: "POST", Path: "/api/v2/ams/alerts/{id}/notes", Capability: "ops", Body: true},
		{Action: "update_note", Help: "change note params.note_id of alert id.", Method: "PUT", Path: "/api/v2/ams/alerts/{id}/notes/{note_id}", Capability: "ops", Body: true},
	},
	"freshservice_journey": {
		{Action: "create_request", Help: "start a journey; body {config_id, requested_for, data: {...}} per config_fields.", Method: "POST", Path: "/api/v2/journeys/requests", Capability: "ops", Body: true},
		{Action: "update_request", Help: "change journey request id.", Method: "PATCH", Path: "/api/v2/journeys/requests/{id}", Capability: "ops", Body: true},
		{Action: "cancel_request", Help: "cancel journey request id.", Method: "PUT", Path: "/api/v2/journeys/requests/{id}/cancel", Capability: "ops", Body: true},
	},
	"freshservice_custom_object": {
		{Action: "create_record", Help: "add a record to custom object id; body {data: {...}} with the object's fields.", Method: "POST", Path: "/api/v2/objects/{id}/records",
			Capability: "custom-objects", Body: true, Require: []string{"data"}},
		{Action: "update_record", Help: "change record params.record_id of custom object id; body {data: {...}}.", Method: "PUT", Path: "/api/v2/objects/{id}/records/{record_id}",
			Capability: "custom-objects", Body: true},
	},
	"freshservice_agent": {
		{Action: "set_delegation", Help: "delegate user id's approvals to another agent; body {delegatee_id, start_time, end_time}.", Method: "POST",
			Path: "/api/v2/users/{id}/delegation", Capability: "approvals", Body: true},
		{Action: "update_delegation", Help: "change user id's approval delegation.", Method: "PUT", Path: "/api/v2/users/{id}/delegation", Capability: "approvals", Body: true},
	},
}
